---
- hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - debug:
        msg: "User in integration is {{ lookup('ini', 'user section=integration file=data/users.ini') }}"
    - debug:
        msg: "User in production  is {{ lookup('ini', 'user section=production  file=data/users.ini') }}"
