---
- hosts: lb
  remote_user: web
  gather_facts: no
  vars:
      random_number1: "{{ 10000 | random }}"
      random_number2: "{{ 10000000000 | random }}"
  tasks:

  - name: Copy the /etc/hosts to /tmp/hosts.{{ random_number1 }}
    copy: src=/etc/hosts dest=/tmp/hosts.{{ random_number1 }}
    notify:
      - define the 3nd handler

  - name: Copy the /etc/hosts to /tmp/hosts.{{ random_number2 }}
    copy: src=/etc/hosts dest=/tmp/hosts.{{ random_number2 }}
    notify:
      - define the 2nd handler
      - define the 1nd handler

  handlers:
  - name: define the 1nd handler
    debug: msg="define the 1nd handler"

  - name: define the 2nd handler
    debug: msg="define the 2nd handler"

  - name: define the 3nd handler
    debug: msg="define the 3nd handler"

#  调用的顺序是 3 -》 2 -》 1
#  执行的顺序是 1 -》 2 -》 3